#!/usr/bin/env python3
"""Build Svelte-compatible typed data from evaleu summary + model cards.

Reads:
  - eval/summary.json   (from `uv run evaleu.py summarize`)
  - site/model_cards.json  (model metadata)

Writes:
  - src/lib/data/models.ts    — typed ModelRecord[] export
  - src/lib/data/benchmarks.ts — typed BenchmarkInfo[] export
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SUMMARY_PATH = ROOT / "eval" / "summary.json"
MODEL_CARDS_PATH = ROOT / "site" / "model_cards.json"  # copy or symlink expected
OUTPUT_DIR = Path(__file__).resolve().parent / "src" / "lib" / "data"


def load_json(path: Path) -> dict:
    if not path.exists():
        print(f"[ERROR] File not found: {path}", file=sys.stderr)
        sys.exit(1)
    return json.loads(path.read_text(encoding="utf-8"))


def escape_ts(s: str) -> str:
    """Escape a string for safe TS template literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def build_models_ts(summary: dict, cards: dict) -> str:
    models = summary.get("models", {})

    lines = [
        "// Auto-generated by build_site_data.py — do not edit manually.",
        "",
        "export interface ModelScore {",
        '  seed: number;',
        '  overall: number;',
        '  benchmarks: Record<string, number>;',
        "}",
        "",
        "export interface ModelRecord {",
        '  id: string;',
        '  displayName: string;',
        '  family: string;',
        '  params: string;',
        '  weightsQuant: string;',
        '  kvCache: string;',
        '  upstreamModelId: string | null;',
        '  releaseDateUtc: string | null;',
        '  releaseSourceUrl: string | null;',
        '  siteVisibility: "published" | "draft";',
        '  runs: ModelScore[];',
        '  overallMean: number;',
        '  overallStd: number;',
        '  benchmarkMeans: Record<string, number>;',
        "}",
        "",
        "export const models: ModelRecord[] = [",
    ]

    model_ids = sorted(models.keys())
    for idx, mid in enumerate(model_ids):
        mdata = models[mid]
        card = cards.get(mid, {})
        runs = mdata.get("runs", [])
        benchmarks = mdata.get("benchmarks", {})
        bench_means = {k: v["mean"] for k, v in benchmarks.items()}

        display_name = escape_ts(card.get("display_name", mid))
        family = escape_ts(card.get("family", "Unknown"))
        params = escape_ts(card.get("params", "?"))
        weights_quant = escape_ts(card.get("weights_quant", "F16"))
        kv_cache = escape_ts(card.get("kv_cache", "f16/f16"))
        upstream = card.get("upstream_model_id") or None
        release_date = card.get("release_date_utc") or None
        release_url = card.get("release_source_url") or None
        visibility = card.get("site_visibility", "published")

        lines.append(f'  {{')
        lines.append(f'    id: "{mid}",')
        lines.append(f'    displayName: "{display_name}",')
        lines.append(f'    family: "{family}",')
        lines.append(f'    params: "{params}",')
        lines.append(f'    weightsQuant: "{weights_quant}",')
        lines.append(f'    kvCache: "{kv_cache}",')
        lines.append(f'    upstreamModelId: {json.dumps(upstream)},')
        lines.append(f'    releaseDateUtc: {json.dumps(release_date)},')
        lines.append(f'    releaseSourceUrl: {json.dumps(release_url)},')
        lines.append(f'    siteVisibility: "{visibility}",')

        # runs array
        lines.append(f'    runs: [')
        for run in runs:
            seed = run["seed"]
            overall = round(run["overall"], 6)
            by_bench = run.get("by_benchmark", {})
            bench_str = ", ".join(
                f'"{escape_ts(k)}": {round(v, 6)}' for k, v in sorted(by_bench.items())
            )
            lines.append(f'      {{ seed: {seed}, overall: {overall}, benchmarks: {{{bench_str}}} }},')
        lines.append(f'    ],')

        lines.append(f'    overallMean: {round(mdata["overall_mean"], 6)},')
        lines.append(f'    overallStd: {round(mdata["overall_std"], 6)},')

        bench_means_str = ", ".join(
            f'"{escape_ts(k)}": {round(v["mean"], 6)}' for k, v in sorted(benchmarks.items())
        )
        lines.append(f'    benchmarkMeans: {{{bench_means_str}}},')
        comma = "," if idx < len(model_ids) - 1 else ""
        lines.append(f'  }}{comma}')

    lines.append("];")
    return "\n".join(lines)


def build_benchmarks_ts(summary: dict, cards: dict) -> str:
    models = summary.get("models", {})
    benchmarks = {}

    # Collect all benchmark names and aggregate means across models
    for mid, mdata in models.items():
        bench_means = mdata.get("benchmarks", {})
        for bname, info in bench_means.items():
            if bname not in benchmarks:
                benchmarks[bname] = {"means": [], "stds": []}
            benchmarks[bname]["means"].append(info["mean"])
            benchmarks[bname]["stds"].append(info.get("std", 0))

    lines = [
        "// Auto-generated by build_site_data.py — do not edit manually.",
        "",
        "export interface BenchmarkInfo {",
        '  name: string;',
        '  shortName: string;',
        '  meanAcrossModels: number;',
        '  stdAcrossModels: number;',
        '  modelCount: number;',
        "}",
        "",
        "export const benchmarks: BenchmarkInfo[] = [",
    ]

    bnames = sorted(benchmarks.keys())
    for idx, bn in enumerate(bnames):
        info = benchmarks[bn]
        means = info["means"]
        stds = info["stds"]
        n = len(means)
        overall_mean = round(sum(means) / n, 6) if n else 0
        overall_std = round((sum((x - overall_mean) ** 2 for x in means) / n) ** 0.5, 6) if n > 1 else 0

        # Short name: remove prefix like "BasqueGLUE_" or "LatxaEval_"
        short = bn
        for prefix in ("BasqueGLUE_", "LatxaEval_", "Eus", "XNLI"):
            if short.startswith(prefix):
                short = short[len(prefix):]
                break

        lines.append(f'  {{')
        lines.append(f'    name: "{bn}",')
        lines.append(f'    shortName: "{short}",')
        lines.append(f'    meanAcrossModels: {overall_mean},')
        lines.append(f'    stdAcrossModels: {overall_std},')
        lines.append(f'    modelCount: {n},')
        comma = "," if idx < len(bnames) - 1 else ""
        lines.append(f'  }}{comma}')

    lines.append("];")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Svelte-compatible TS data from evaleu summary")
    parser.add_argument("--summary", default=str(SUMMARY_PATH), help="Path to summary.json")
    parser.add_argument("--cards", default=str(MODEL_CARDS_PATH), help="Path to model_cards.json")
    parser.add_argument("--out-dir", default=str(OUTPUT_DIR), help="Output directory for TS files")
    args = parser.parse_args()

    summary_path = Path(args.summary)
    cards_path = Path(args.cards)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    summary = load_json(summary_path)
    cards = load_json(cards_path) if cards_path.exists() else {}

    # Generate models.ts
    models_ts = build_models_ts(summary, cards)
    (out_dir / "models.ts").write_text(models_ts + "\n", encoding="utf-8")
    print(f"[OK]  src/lib/data/models.ts ({len(models_ts.splitlines())} lines)")

    # Generate benchmarks.ts
    bench_ts = build_benchmarks_ts(summary, cards)
    (out_dir / "benchmarks.ts").write_text(bench_ts + "\n", encoding="utf-8")
    print(f"[OK]  src/lib/data/benchmarks.ts ({len(bench_ts.splitlines())} lines)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
